server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: jwt
    password: 1234
    
  jpa:
    hibernate:
      ddl-auto: create 
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
   oauth2:
    client:
     registration:
      google:
       client-id: 881387959375-td87djvnb9aufrkd0fgdfhkevq9mgpvf.apps.googleusercontent.com
       client-secret: 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
       scope:
       - email
       - profile

      naver:
       client-id: jwL8LelJ9jttO7bgqr8A
       client-secret: j5WiRyp6PS
       scope:
       - name
       - email
       client-name: Naver
       authorization-grant-type: authorization_code
       redirect-uri: http://localhost:8080/login/oauth2/code/naver

     provider:
      naver:
       authorization-uri: https://nid.naver.com/oauth2.0/authorize # '네이버 로그인' 서비스 요청 resource
       token-uri: https://nid.naver.com/oauth2.0/token # 접근 토큰 발급을 요청할 수 있는 resource
       user-info-uri: https://openapi.naver.com/v1/nid/me # 유저 정보를 요청할 수 있는 resource
       user-name-attribute: response # 회원정보를 json으로 받는데 repsonse라는 키값으로 네이버가 리턴해줌

